<?php

/**
 * @file
 * Primary module hooks for OAFC License Notifications module.
 */

use Drupal\Core\Url;
use Drupal\Core\Render\Markup;
use Drupal\Core\Form\FormStateInterface;

/**
 * Implements hook_entity_type_build().
 */
function oafc_license_notifications_entity_type_build(array &$entity_types) {
  /** @var \Drupal\Core\Entity\EntityTypeInterface[] $entity_types */
  if (isset($entity_types['commerce_license'])) {
    $entity_types['commerce_license']->setClass('Drupal\\oafc_license_notifications\\Entity\\License');
  }
}

/**
 * Implements hook_mail().
 */
function oafc_license_notifications_mail($key, &$message, $params) {
  switch ($key) {
    case 'license_expiration_warning':
      $message['headers'] = array_merge($message['headers'], $params['headers']);
      $message['from'] = $params['from'];
      $message['subject'] = $params['subject'];
      $message['body'][] = Markup::create($params['body']);
      break;
  }
}

/**
 * Implements hook_cron().
 */
function oafc_license_notifications_cron() {
  /** @var \Drupal\oafc_license_notifications\LicenseExpirationChecker $checker */
  $checker = \Drupal::service('oafc_license_notifications.license_checker');
  $checker->checkExpiringLicenses();
}

/**
 * Implements hook_theme().
 */
function oafc_license_notifications_theme($existing, $type, $theme, $path) {
  return [
    'oafc_license_expiration_notification' => [
      'variables' => [
        'license' => NULL,
        'owner' => NULL,
        'days_until_expiration' => NULL,
        'expiry_date' => NULL,
        'purchased_entity' => NULL,
        'purchased_entity_url' => NULL,
        'renew_url' => NULL,
      ],
    ],
  ];
}

/**
 * Implements hook_form_FORM_ID_alter().
 *
 * We are targeting the 'user_login_form'.
 */
function oafc_license_notifications_form_user_login_form_alter(&$form, FormStateInterface $form_state, $form_id) {
  // Add a submit handler to process the 'destination' parameter for redirecting
  // the user after login.
  $form['#submit'][] = 'oafc_license_notifications_submit_handler';
}

/**
 * Custom submit handler for the user_login_form.
 *
 * This function checks for a valid 'destination' parameter and
 * overrides any previously set redirect. This ensure that users are properly
 * redirected to the membership renewal page after logging in, if they're coming
 * from a license expiration notification email.
 */
function oafc_license_notifications_submit_handler($form, FormStateInterface $form_state) {
  $current_request = \Drupal::requestStack()->getCurrentRequest();
  $request_uri = $current_request->getRequestUri();

  // Check if the 'destination' query parameter exists.
  if ($request_uri && strpos($request_uri, 'destination=') !== FALSE) {
    // Parse out the destination url.
    $destination_url = substr($request_uri, strpos($request_uri, 'destination=') + strlen('destination='));
    $destination_url_parts = parse_url(urldecode($destination_url));

    // Check if the destination has a 'host' and if the site host is part of it.
    $request_host = $current_request->getHost();
    if ($destination_url_parts && isset($destination_url_parts['host']) && $destination_url_parts['host'] === $request_host) {
      // Set the redirect URL.
      $url = Url::fromUserInput($destination_url_parts['path'] ?? '/');
      $form_state->setRedirectUrl($url);
    }
  }
}
